### ISSUE TITLE
Move Smarty and Twig into their own repos

### ISSUE THREAD

**Issue by RobLoach** [phptransformers/phptransformer#26]

**Comment by glensc** [comment]
looks incomplete. at least i would expect readme to install extra packages, i.e `composer require sometihng/else`

**Comment by MacFJA** [comment]
@glensc This repository is more a _spec_ or an interface definition (like [php-fig/log](https://github.com/php-fig/log))

But you right, the readme is maybe not clear enough about this.
Some `suggest` entry in the composer.json will be a good addition too.

**Comment by RobLoach** [comment]
> Some suggest entry in the composer.json will be a good addition too.

:+1:
