### ISSUE TITLE
Plates

### ISSUE THREAD

**Issue by RobLoach** [phptransformers/phptransformer#5]
http://platesphp.com/

**Comment by MacFJA** [comment]
Here my implementation: https://github.com/MacFJA/phptransformer-plates :wink:

**Comment by RobLoach** [comment]
Nice! Just gave you access on the Org if you want them hosted in the organization :+1: .

**Comment by MacFJA** [comment]
Repo moved to PhpTransformers (https://github.com/phptransformers/plates), but I can't change the Packagist data (still link to my own account, and I can't use the **phptransformers**).
@RobLoach : Can you do it?

**Comment by MacFJA** [comment]
The transformer is available here: [plates](https://github.com/phptransformers/plates)
